### ISSUE TITLE
Error decrypting the database

### ISSUE THREAD

**Issue by husenko** [aramosf/pwncrypt5#1]
Database from device Samsung Galaxy S4 I9500.
Whatsapp version 2.11.195
Active Python 2.6.7
M2Crypto 0.21.1
Error details:

Traceback (most recent call last):
  File "C:\Whatsapp\pwncrypt5.py", line 33, in <module>
    decrypt(sys.argv[1],sys.argv[2])
  File "C:\Whatsapp\pwncrypt5.py", line 27, in decrypt
    sys.stdout.write(cipher.final())
  File "C:\Python27\lib\site-packages\M2Crypto\EVP.py", line 128, in final
    return m2.cipher_final(self.ctx)
M2Crypto.EVP.EVPError: bad decrypt

**Comment by Arathp** [comment]
Jjkk
